apiVersion: v1
data:
  PING_IDENTITY_ACCEPT_EULA: "YES"
  SERVER_PROFILE_PATH: getting-started/pingfederate
  SERVER_PROFILE_URL: https://github.com/pingyasin/lab-profiles.git
kind: ConfigMap
metadata:
  labels:
    role: pingfederate
  name: pingfederate-environment-variables